### ISSUE TITLE
Not an issue more a request: Could you please please add it to the aur?

### ISSUE THREAD

**Issue by jackhistoria** [dac1976/IP-Freely#2]
I am new to 3rd party libraries like boost, loki.. and still learning to program (and compile) in qt and I asked myself, why didn't you use e.G. the `QFileSystem` and `QSerial`, is boost that much better? 

I still struggle compiling your CoreLibrary, gave it up last night but will pick it up again following the other issue here at times. I already tried to fix the paths with the project pointing to the `QtProject folder`, would pull an issue on the CoreLibrary repository. 
Still doesn't want to find the libraries somehow even they are there and the project file points to them 

So fare I found the other libraries on [arch linux AUR's e.G. with yay](https://www.tecmint.com/install-yay-aur-helper-in-arch-linux-and-manjaro/):
`yay -S boost boost-libs cereal loki-lib qt qt5-singleapplication opencv`

You are such an experienced programmer, wouldn't it be a few minutes work for you to just create an AUR for it? I tried the other solutions for rtsp cameras compared to your work they are really messy and/or inefficient. 

**My confirmed guess is, lots of people would benefit of your work.** 

When/if I got your projects up and running and you didn't had the time or intention to create an AUR I would figure that out with your permission. The same for your CoreLibrary package you created. Also helping with bug fixes according to your trello list since this is a cool project would be an honor.

What do you think? Thanks upfront for your time and work you already put into this.

**Comment by dac1976** [comment]
Thanks for the comments. You have multiple options to link to the third party libraries if using Qt. One is to use my included example makespecs for Qt and adjust these to match the locations of the libraries on your PC. Then copy these makespecs into Qt's makespecs folder then restart Qt. Then you can add these makespecs to your Qt project with the CONFIG += <makespec name> option. Or you can directly link to the libraries in your Qt project using LIBS += and INCLUDES += and so on. I would say before jumping in with both feet make sure you are familiar with how to set these sorts of things in Qt. As for using boost and pure C++1x code for things like CoreLibrary...the reason is that code is cross-platform, cross-compiler code. I have slightly modified versions of this code in use commercially in Windows software built in Visual Studio, Embarcadero C++ Builder, MinGW, Clang and Qt. I also have it running in desktop Linux on Ubuntu and Manjaro built with GCC and clang and also on ARM based devices running Debian built with gcc. For this reason and as the code doesn't take long to build I provide it as is and people can build it for their needs as they see fit, as long as they comply with the license terms. Sadly I have very little spare time to build and maintain binary packages, as it were, targeting different user environments and operating systems.

**Comment by dac1976** [comment]
Also I have some info on the wiki part of this repo about building with Qt and where to put makespecs.

**Comment by dac1976** [comment]
The wiki I refer to is on my CoreLibrary project, realised I hadn't been clear about that.

**Comment by jackhistoria** [comment]
@dac1976 Chellange accepted - thanks for your detailed answers, I really appreciate it. 

Will take some time on my side but will be worth it. Working through _`Nicholas Sherriff (Nick) - Learn Qt 5_ Build modern, responsive cross-platform desktop applications with Qt, C++, and QML-Packt Publishing (2018)`_ right now and the project file / make-specs side is already looking familiar. Just a matter of time ill guess and I got it and will report back and do what I promised. 
Also thanks for the hint on your core lib wiki. 
On my research I found the VLC-player lib ([LibVLC](https://stackoverflow.com/questions/45121618/qt-5-and-libvlc#45122693)) that might make this project even more extensive, but one step at a time. 
Pretty excited rn. Stay healthy
